# Generated by Django 3.2.4 on 2021-06-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='ano_fabricacao',
            field=models.CharField(default='1990', max_length=4),
        ),
        migrations.AddField(
            model_name='garagem',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='garagem',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
